denoland/deno_graph

Cargo.lock
Cargo.toml
README.md
src/ast.rs
src/graph.rs
src/info.rs
src/js_graph.rs
src/lib.rs
src/source.rs
src/text_encoding.rs

This adds a new public `parse_module_from_ast` function and `AstParser` trait.
~~Depends on #12, so diff is noisy right now.~~

feat: add `AstParser` trait

---

mod.ts

fix: export ModuleGraphJson

---

src/lib.rs

Useful for embedders implementing custom resolvers .

feat: expose resolve_import

---

lib/types.d.ts
mod.ts
test.ts

Was upgrading to the latest std and it surfaced some bugs because now it type checks the expected values in assertions.

fix(types): add missing `ModuleKind` values and `DependencyJson` property

---

src/npm.rs

From https://github.com/denoland/deno/pull/17272/files#diff-37eccd30b5732ee9a5aeca31a10b97ecd200cb8e5346c22f122183f7e1dce237R148

feat: add sorting for `NpmPackageReq`

---

src/graph.rs

There are some pre-allocations we're not doing in the CLI because we don't have this information.

feat: add specifiers_count() for getting the approximate number of specifiers in the graph

---

.github/workflows/ci.yml

I published a release manually. Seems to work other than this.
https://github.com/denoland/deno_graph/actions/runs/4511675381/jobs/7944107510

ci: maybe fix tagging

---

.github/workflows/ci.yml

ci: use denoland/publish-folder action for publishing to deno.land/x

---

Cargo.lock
Cargo.toml
lib/Cargo.toml

~~Waiting on https://github.com/denoland/deno_semver/pull/5~~

refactor: upgrade to deno_semver 0.3

---

lib/lib.rs
src/ast.rs
src/graph.rs
src/module_specifier.rs
src/source.rs

Will make moving a check to a higher level easier in https://github.com/denoland/deno_graph/pull/295 (will comment there soon)

feat: add ResolveError type

---

src/type_tracer/analyzer.rs
src/type_tracer/cross_module.rs
tests/specs/type_tracing/Classes01.txt
tests/specs/type_tracing/ExportDefaultLiteral01.txt
tests/specs/type_tracing/ExportDefaultLiteral02.txt
tests/specs/type_tracing/ExportedDeclare01.txt
tests/specs/type_tracing/ExportedDeclare02.txt
tests/specs/type_tracing/ReexportExport.txt

feat(tracing): support default expr literals

---

src/type_tracer/analyzer.rs
tests/specs/type_tracing/ExportDestructured.txt

Increases the resolution of what's exposed.

feat(tracing): expose ident of variable node

---

src/graph.rs
src/packages.rs
tests/integration_test.rs
tests/specs/graph/JsrSpecifiers_InvalidExport.txt
tests/specs/graph/JsrSpecifiers_ModuleGraphInfo.txt
tests/specs/graph/JsrSpecifiers_ModuleGraphInfo_ModifiedCachedFiles.txt
tests/specs/graph/JsrSpecifiers_NoModuleGraphInfo.txt
tests/specs/graph/JsrSpecifiers_SamePackageMultipleTimes.txt
tests/specs/graph/JsrSpecifiers_WorkspaceNoExports.txt
tests/specs/graph/JsrSpecifiers_WorkspaceNotMatched.txt

Adds a requirement for packages to define exports.

feat(jsr): add package exports

---

src/graph.rs

Was upgrading dnt and ran into this issue.

feat: `ModuleError` - `to_string_with_range()`

---

Cargo.lock
Cargo.toml

Updates `import_map` crate needed for https://github.com/denoland/deno/pull/20410

chore: update import_map to 0.17.0

---

Cargo.lock
Cargo.toml
src/analyzer.rs
src/ast.rs
src/graph.rs
src/lib.rs
tests/specs/graph/JsrSpecifiers_ModuleGraphInfo.txt
tests/specs/graph/JsrSpecifiers_ModuleGraphInfo_ModifiedCachedFiles.txt
tests/specs/graph/JsrSpecifiers_SamePackageMultipleTimes.txt

Pre-requisite for https://github.com/denoland/deno_graph/issues/275

refactor: switch to dep_analysis feature in deno_ast

---

src/fast_check/transform.rs
src/symbols/dep_analyzer.rs
tests/specs/graph/JsrSpecifiers_FastCheck_TypeAssertion.txt

For https://github.com/denoland/deno/issues/21894

fix(fast_check): analyze identifiers in type assertions/as exprs

---

Cargo.lock
Cargo.toml
src/graph.rs
src/packages.rs
src/source/mod.rs
tests/integration_test.rs
tests/specs/graph/JsrSpecifiers_ModuleGraphInfo.txt
tests/specs/graph/JsrSpecifiers_ModuleGraphInfo_ModifiedCachedFiles.txt
tests/specs/graph/JsrSpecifiers_NoModuleGraphInfo.txt
tests/specs/graph/JsrSpecifiers_SamePackageMultipleTimes.txt

Enables https://github.com/denoland/deno_lockfile/pull/13
~~Waiting on https://github.com/denoland/deno_semver/pull/15~~
~~Waiting on https://github.com/denoland/deno_semver/pull/17 but this is good for review.~~

feat: store JSR package constraints of packages in graph

---

src/fast_check/transform.rs
tests/specs/graph/JsrSpecifiers_FastCheck_Comments.txt
tests/specs/graph/JsrSpecifiers_FastCheck_NestedJavaScriptDeclFile.txt

fix: keep @ts- comments

---

src/fast_check/mod.rs
src/symbols/dep_analyzer.rs
tests/specs/graph/JsrSpecifiers_FastCheck_Issue22544.txt

Will fix: https://github.com/denoland/deno/issues/22544

fix(fast_check): analyze computed interface members

---

src/fast_check/mod.rs
src/source/mod.rs

This was annoying in the CLI
Need to fix my git history lol

fix: implement PartialEq and Eq for ResolutionMode

---

src/ast.rs

fix(analyzer): skip hashbang comment

---

src/fast_check/transform.rs
tests/specs/graph/jsr/FastCheck_ClassPropertiesWithTsPrivate.txt

For https://github.com/denoland/deno/issues/23334

fix(fast_check): ts private property with `declare` should not keep non-null assertion

---

src/ast.rs

For use with https://github.com/denoland/deno_ast/pull/237

feat: ability to remove from a `ParsedSourceStore`

---

Cargo.lock
Cargo.toml
src/fast_check/mod.rs
src/fast_check/transform.rs

Publish broke because of deno_ast changes.
https://github.com/denoland/deno_graph/actions/runs/8673943975/job/23785750308

fix: update for deno_ast changes

---

src/fast_check/transform.rs
tests/specs/graph/fast_check/import_equals.txt

For https://github.com/denoland/deno/issues/23388

fix(fast_check): support import equals

---

rust-toolchain.toml
src/fast_check/range_finder.rs
src/graph.rs
src/symbols/analyzer.rs
tests/specs_test.rs

`cargo publish` strikes again.
https://github.com/denoland/deno_graph/actions/runs/9289612056/job/25563934229

fix: upgrade to rust 1.78 to fix publish

---

src/source/mod.rs

perf: remove unnecessary heap allocation in `recommended_registry_package_url_to_nv`

---

src/graph.rs
src/lib.rs

Fixes https://github.com/denoland/deno_graph/pull/530#discussion_r1774189525
Tested this in the CLI and it works much better.

fix: improve walk

---

src/fast_check/transform.rs
tests/specs/ecosystem/hampus/itsdangerous/1_1_0.test
tests/specs/ecosystem/hampus/itsdangerous/1_1_1.test
tests/specs/ecosystem/hampus/itsdangerous/1_1_2.test
tests/specs/ecosystem/kwhinnery/animals/0_0_14.test
tests/specs/ecosystem/kwhinnery/animals/0_0_15.test
tests/specs/graph/fast_check/auto_accessors.txt
tests/specs/graph/fast_check/class_ctors.txt
tests/specs/graph/fast_check/class_methods_with_ts_private.txt
tests/specs/graph/fast_check/class_overrides.txt
tests/specs/graph/fast_check/class_properties.txt
tests/specs/graph/fast_check/class_properties_with_ts_private.txt

For https://github.com/denoland/deno/issues/25322

fix(fast_check): better `override` handling

---

Cargo.lock
Cargo.toml
src/ast.rs

* Waiting on https://github.com/denoland/deno_ast/pull/286
* Towards https://github.com/denoland/deno/issues/26651

fix: compute whether script

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
rust-toolchain.toml

(for later)
Reverts denoland/deno_graph#548

Reland "chore: upgrade deno_ast, deno_semver, thiserror"

---

Cargo.lock
Cargo.toml
src/source/wasm.rs
tests/specs/ecosystem/mrii/rocket_io/0_1_3.test

100,000 iterations of the `test_output` test.
Before: 218ms
After: 179ms

perf: improve wasm_module_deps_to_dts

---

lib/lib.rs
src/graph.rs
src/lib.rs
src/source/mod.rs
tests/specs/ecosystem/mrii/rocket_io/0_1_3.test

Towards https://github.com/denoland/deno/pull/27009.

feat: provide referrer when requesting jsx config

---

lib/lib.rs
src/graph.rs
tests/ecosystem_test.rs
tests/helpers/mod.rs
tests/specs/graph/skip_dynamic_deps.txt
tests/specs_test.rs

Adds the ability to skip loading statically analyzable dynamic dependencies.
Towards https://github.com/denoland/deno/issues/28581

feat: ability to skip loading statically analyzable dynamic dependencies

---

Cargo.lock
Cargo.toml

This is to ensure the tests still pass.

chore: deno_ast 0.46.3

---

src/collections.rs
src/graph.rs
src/lib.rs
tests/helpers/mod.rs
tests/integration_test.rs

Moved out of https://github.com/denoland/deno_graph/pull/581
For:
* https://github.com/denoland/deno/issues/28254

feat: ability to remove types from the graph

---

src/graph.rs
tests/integration_test.rs

revert: "fix: respect lockfile when loading jsr specifiers"

---

tests/specs/ecosystem/bureaudouble/sonner/0_0_1.test
tests/specs/graph/jsr/entrypoint.txt
tests/specs_test.rs

Was looking into an issue and realized it's not in this repo. That said, wrote this test so might as well keep it.

chore: test for jsr specifier entrypoint

---

src/graph.rs
tests/specs/graph/bytes_and_text/redirect.txt

For https://github.com/denoland/deno/issues/29927

fix: make bytes and text import work if redirected

---

src/graph.rs
tests/helpers/mod.rs
tests/integration_test.rs

Part of surfacing these errors again when necessary for https://github.com/denoland/deno/pull/29926

fix: do not surface types resolution failures for side effect imports

---

.github/workflows/release.yml

https://github.com/denoland/automation/releases/tag/0.22.1

chore: fix release publish again
