src/js_graph.rs, src/lib.rs
I realised that I needed to expose a couple of structs when using in other crates which are targetting web assembly as well.
=> feat: expose js api with wasm feature

src/ast.rs, src/lib.rs
Just thought of this. Basically by default it won't build up so much in memory in a `HashMap`, but someone can provide a `CapturingAstParser` to store the ASTs.
=> feat: `DefaultAstParser` that uses less memory and add `CapturingAstParser`

src/source.rs
This function is useful to implementers. It should be exposed.
=> chore: expose `load_data_url`

src/graph.rs, src/js_graph.rs, src/source.rs
This commit removes the need to explicitly return the passed in
specifier from the returned source::Loader::load function at the cost of
one extra heap allocation.
=> Make source::Loader easier to use

.devcontainer/Dockerfile
This updates the version of the wasm-bindgen-cli to match the version needed by the `Cargo.toml`.
=> chore: update devcontainer config

.github/workflows/release.yml
This is my last attempt before temporarily giving up on this. This change makes the version bump script use `--force-with-lease`, which might allow bypassing the status checks (for this script, we don't care about status checks because it's just bumping the version, which should succeed status checks).
=> chore: maybe fix release script's ability to bypass status checks

src/graph.rs, src/lib.rs
Moving code from https://github.com/denoland/deno/blob/main/cli/graph_util.rs
=> feat: add ModuleGraph segment and walk

src/semver/mod.rs
In the npm dependency resolution code we're constantly parsing strings to `Versions`. If we instead serialized/deserialized this as a string then we could use `Version` on the npm package info struct directly in order to parse the versions a single time.
=> feat: serialize and deserialize `Version` as string

src/graph.rs, src/lib.rs, src/source.rs, tests/integration_test.rs
This is going to help with cache busting npm specifiers more aggressively in the CLI.
CLI PR: https://github.com/denoland/deno/pull/18636
=> feat: support restarting npm resolution on resolution failure

src/graph.rs
This is preventing the LSP hover text on repeated imports from including certain dependency information: https://github.com/denoland/deno/blob/5a524a9a5a7fac0d16b2cbe2df1142dc419df7fc/cli/lsp/documents.rs#L603.
=> fix: check all import ranges in Dependency::includes()

README.md, _build_npm.ts, src/graph.rs, src/lib.rs, tests/integration_test.rs
We should be forced to think about what kind of graph we're creating whenever we create one for performance reasons.
=> refactor: remove the default implementation of ModuleGraph

src/type_tracer/analyzer.rs, src/type_tracer/mod.rs, tests/integration_test.rs, tests/specs/type_tracing/Basic.txt, tests/specs/type_tracing/Classes01.txt, tests/specs/type_tracing/ExportAssignment01.txt, tests/specs/type_tracing/ExportDefault01.txt, tests/specs/type_tracing/ExportDefault02.txt, tests/specs/type_tracing/ExportDefault03.txt, tests/specs/type_tracing/ExportDefault04.txt, tests/specs/type_tracing/ExportStar01.txt, tests/specs/type_tracing/Functions01.txt, tests/specs/type_tracing/ImportEquals01.txt, tests/specs/type_tracing/ImportEquals02.txt, tests/specs/type_tracing/ImportType01.txt, tests/specs/type_tracing/ImportType02.txt, tests/specs/type_tracing/Interfaces01.txt, tests/specs/type_tracing/Interfaces02.txt, tests/specs/type_tracing/ModuleExportNameStr01.txt, tests/specs/type_tracing/TsExternalModuleRef01.txt, tests/specs/type_tracing/TsExternalModuleRef02.txt, tests/specs/type_tracing/TsNamespaceExport01.txt, tests/specs/type_tracing/TsQualifiedName01.txt, tests/type_tracing/mod.rs, tests/type_tracing/test_builder.rs, tests/type_tracing/tests.rs
Improves the functionality in https://github.com/denoland/deno_graph/pull/278 to store the traced referrers. This is useful for declaration emit in order to tell which modules import a remote dependency and what names they import.
=> feat(type_tracing): store the traced referrers

Cargo.lock, Cargo.toml
data-url -> 0.3.0
indexmap -> 2
Also, run `cargo update`
=> chore: bump some deps we're bumping in deno

lib/lib.rs, src/graph.rs, src/source.rs, tests/helpers/test_builder.rs, tests/integration_test.rs
As I started integrating this downstream, I realized some things that were done could be improved.
=> feat: LoaderCacheSetting -> CacheSetting

README.md
The example in README looks outdated. This PR updates it.
=> docs(README): update MemoryLoader example

lib/lib.rs, src/graph.rs, src/lib.rs, src/module_specifier.rs, src/source.rs, tests/integration_test.rs
part of https://github.com/denoland/deno/issues/20566
This PR updates the resolution of bare specifiers. If the module specifier is node builtin module as a bare specifier, resolve it as `node:<module_name>`. Also it prints the warning message like `Warning: Resolving "path" as "node:path". If you want to use a built-in Node module, add a "node:" prefix.`
=> feat: resolve node builtin module without node: scheme

src/graph.rs, src/lib.rs, src/source.rs, tests/integration_test.rs
This PR passes `Range` to `on_resolve_bare_builtin_node_module`. This is necessary to implement https://github.com/denoland/deno/pull/20728
=> fix: pass range to on_resolve_bare_builtin_node_module

Cargo.lock, Cargo.toml, src/graph.rs, src/lib.rs
This PR adds bare node specifier check when the `ResolveError` from `resolver.resolve` is `Other(ImportMapError::UnmappedBareSpecifier(_, _))`.
By this change, we can keep more detailed error message from `ImportMapError`, for example, like `Relative import path "unmapped" not prefixed with / or ./ or ../ and not in import map from "file://[WILDCARD]/092_import_map_unmapped_bare_specifier.ts"`
related https://github.com/denoland/deno/pull/20728
=> fix: check bare node specifier for ImportMapError::UnmappedBareSpecifier

src/graph.rs, src/lib.rs, src/source.rs
This PR adds `is_bare_node_specifier_enabled` to `NpmResolver` to enable feature flagging of bare node specifier resolution.
related https://github.com/denoland/deno/pull/20728
=> fix: add is_bare_node_specifier_enabled to NpmResolver trait

lib/lib.rs, src/graph.rs, src/lib.rs, src/source.rs
This is necessary for BYONM so that I can tell if "types" resolution is currently being done or "code"/"execution" resolution. With node resolution we could end up at different files based on what resolution is being done (unlike with Deno resolution, which is much simpler).
=> feat(resolver): add resolution mode

js/test.ts, src/graph.rs, src/lib.rs
Makes https://github.com/denoland/deno_graph/pull/303 actually work.
=> fix(resolver): resolution with ResolutionMode::Types should be attempted

lib/lib.rs, src/graph.rs, src/lib.rs
It seems when GraphKind::CodeOnly we were doing a lot of extra work that we didn't need to do. This should make things faster when just running without type checking.
I noticed this while working on https://github.com/denoland/deno_graph/pull/304
Also closes #266
=> perf: do not resolve more types when GraphKind::CodeOnly

src/type_tracer/analyzer.rs, src/type_tracer/cross_module.rs, tests/specs/type_tracing/DeclarationMerging01.txt, tests/specs/type_tracing/FunctionOverloads01.txt, tests/specs/type_tracing/Functions01.txt
This is for deno_doc for analyzing implementation signatures.
=> feat(tracing): include fn implementation signatures in list of symbol declarations

src/graph.rs, src/lib.rs
Adds a new `TypesResolutionError` so that it's easier to identify which resolution errors are for type checking or not and enhance the error messages.
FYI @nayeemrmn. For some reason I can't add you as a reviewer.
=> feat: add ModuleGraphError::TypesResolutionError

src/graph.rs, src/lib.rs
This code from deno_doc is useful for general use.
https://github.com/denoland/deno_doc/blob/bb11d9e8eeddaa7fe26b14fc7b5463cd042fc550/src/parser.rs#L1181
=> feat: ability to easily get types module from graph

src/graph.rs
This helps add some stability in error messages and in the future order might matter.
=> fix(workspace): use IndexMap instead of HashMap for exports

Cargo.lock, Cargo.toml, lib/lib.rs, src/graph.rs, src/lib.rs, src/source/file_system.rs, src/source/mod.rs, tests/integration_test.rs
1. This does not have a directory entry limit.
2. This swallows errors.
Closes https://github.com/denoland/deno_graph/issues/275
=> feat: include some possible dynamic imports with template literals in graph

src/lib.rs
=> fix: export new analyzer types

src/graph.rs, src/module_specifier.rs, tests/integration_test.rs
Some changes for the dynamic import search.
1. Sort the specifiers so the output is stable.
2. Ignore specifiers like `file:///${expr}` because that will include the root dir
=> fix(read_dir): analyze deps stably and do not analyze root dir

lib/lib.rs, src/graph.rs, src/lib.rs, src/source/mod.rs
This allows me to display a warning when resolving an `--unstable-loose-import`.
=> feat: expose referrer's `Range` in `Resolver`

src/graph.rs, tests/integration_test.rs
I think the dynamic argument module search should ignore certain folder names as they are almost guaranteed to not be wanted. This excludes hidden folders and folders named `node_modules` or `vendor`.
=> fix: dynamic arg module search should ignore specific folder names

src/symbols/cross_module.rs, tests/specs/symbols/ReexportDeep.txt
Closes https://github.com/denoland/deno_graph/issues/351
=> fix(symbols): better handling of deep re-exports

src/fast_check/mod.rs, src/fast_check/range_finder.rs, src/fast_check/transform.rs, src/graph.rs, tests/integration_test.rs, tests/specs/graph/JsrSpecifiers_FastCheck_EntrypointJs.txt, tests/specs/graph/JsrSpecifiers_FastCheck_NestedJavaScript.txt, tests/specs/graph/JsrSpecifiers_FastCheck_NestedJavaScriptDeclFile.txt
=> fix(fast_check): handle JS files, `@deno-types` and triple slash references

src/source/mod.rs, src/text_encoding.rs
Moving this into the CLI allows me to delete some CLI code and re-use the functionality that's already in this crate.
=> feat: move text encoding functionality into `deno_graph::source` from CLI

src/packages.rs
For https://github.com/denoland/deno/pull/22359 and tests will go in there (I'll add tests here once adding the integrity check)
The lockfile always expects these to exist now because we're going to add integrity there.
=> fix: always create a package entry for jsr packages

Cargo.lock, Cargo.toml, js/mod.ts, lib/lib.rs, src/graph.rs, src/packages.rs, src/source/mod.rs, tests/helpers/mod.rs, tests/helpers/test_builder.rs, tests/integration_test.rs, tests/specs/graph/JsrSpecifiers_Checksum_Mismatch.txt, tests/specs/graph/JsrSpecifiers_Checksum_Unsupported.txt, tests/specs/graph/JsrSpecifiers_InvalidExport.txt, tests/specs/graph/JsrSpecifiers_WorkspaceNotMatched.txt, tests/specs/graph/Jsr_ImportViaHttps.txt
This loads individual files in the package using the checksum found in the package's manifest. This allows us to reduce the amount of information we need to store in the lockfile.
=> feat: load JSR URLs using checksum found in package's manifest

js/test.ts, lib/lib.rs
Remembered about this while writing something similar in eszip. Seems like we had no tests.
=> fix(js): correct passing of load options from Rust

src/fast_check/range_finder.rs, src/symbols/analyzer.rs, tests/specs/graph/JsrSpecifiers_FastCheck_EntrypointJsWithTsDecl.txt, tests/specs/graph/JsrSpecifiers_FastCheck_JsWithTsDecl.txt, tests/specs/symbols/TypeScriptTypesHeader.txt, tests/specs/symbols/TypesEntrypoint.txt
It was actually improperly doing this. I discovered while doing some refactors in the CLI.
=> fix(fast-check): do not add warning diagnostic for js entrypoint with types

src/fast_check/swc_helpers.rs, src/fast_check/transform.rs, src/fast_check/transform_dts.rs, src/lib.rs, tests/specs/graph/JsrSpecifiers_FastCheck_Dts.txt, tests/specs/graph/JsrSpecifiers_FastCheck_NestedJavaScriptDeclFile.txt
Closes https://github.com/denoland/deno_graph/issues/373
=> fix: handle dts files in fast check

src/graph.rs, tests/specs/graph/JsrSpecifiers_VersionTagNotSupported.txt
When a jsr specifier is used, an error is returned if the version segment contains a tag.
Fixes: https://github.com/denoland/deno/issues/22420
=> fix: jsr specifier does not support tags

src/analyzer.rs, src/ast.rs, tests/specs/graph/JsrSpecifiers_ModuleGraphInfo.txt, tests/specs/graph/JsrSpecifiers_ModuleGraphInfo_ModifiedCachedFiles.txt, tests/specs/graph/JsrSpecifiers_SamePackageMultipleTimes.txt
It is not used. The specifier and argument range seems good enough.
=> perf: remove range on dep descriptor

Cargo.lock, Cargo.toml, lib/Cargo.toml, lib/lib.rs, src/graph.rs, src/lib.rs, src/rt.rs
Adds an abstract trait for executing futures onto an async runtime. 
A default Tokio spawn executor is included behing the `tokio_executor` feature flag.
Closes https://github.com/denoland/deno_graph/issues/394
=> perf: spawn jsr futures on executor

src/fast_check/mod.rs, src/fast_check/range_finder.rs
Fixes a bug I introduced in #401 where modules that are not exports of a pkg that contained a fast check diagnostic would not be invalidated when they changed in all scenarios. This is very tedious to test in deno_graph and much easier to test in integration in the CLI, where this was caught.
I had run the jsr tests in the CLI when I made that change, but maybe I didn't have it hooked up properly and ended up not actually running them on that change.
=> fix(fast_check): regression in cache with diagnostics

src/fast_check/mod.rs, src/fast_check/transform.rs, src/fast_check/transform_dts.rs, tests/specs/graph/JsrSpecifiers_FastCheck.txt, tests/specs/graph/JsrSpecifiers_FastCheck_ClassCtors.txt, tests/specs/graph/JsrSpecifiers_FastCheck_Comments.txt, tests/specs/graph/JsrSpecifiers_FastCheck_Functions.txt, tests/specs/graph/JsrSpecifiers_FastCheck_RefObjType.txt
This was tricky. swc was modifying an Rc<RefCell<T>> in the comments collection during emit as a way of saying "I already emitted this comment", so we need to deep clone it.
=> fix: emit jsdocs in dts emit

src/graph.rs, tests/helpers/test_builder.rs, tests/specs/graph/jsr/DynamicImport.txt, tests/specs/graph/jsr/DynamicImportInvalidChecksum.txt, tests/specs/graph/jsr/ImportViaHttps.txt
We accidentally weren't passing around the version's manifest for dyanmic imports, so it was thinking it was doing an https import from a non-JSR package.
=> fix: relative dynamic imports in jsr packages

.github/workflows/ci.yml, deno.json, js/deno.json
The gitignore will now be correctly taken into account so we need to un-ignore the files in the js directory.
=> chore: fix publishing for jsr

src/fast_check/transform.rs, tests/specs/graph/jsr/FastCheck_TypeAssertion.txt
This PR adds support for inferring the type of an expression initializer for an exported var declaration. This is needed to make branded types work with fast-check and our dts transform.
```ts
// input
export const foo = "foo" as "foo" & { __brand: "foo" };
// Fast check output
export const foo: "foo" & { __brand: "foo" } = {} as any;
// DTS
export const foo: "foo" & { __brand: "foo" };
```
=> feat(fast_check): infer type literals

src/fast_check/transform.rs, tests/specs/graph/jsr/FastCheck_ClassCtors.txt, tests/specs/graph/jsr/FastCheck_ClassMethods.txt
Was writing some integration tests and ran into this.
=> fix(fast_check): handle ts private methods better

src/fast_check/swc_helpers.rs, src/fast_check/transform.rs, tests/specs/graph/jsr/DynamicImport.txt, tests/specs/graph/jsr/FastCheck.txt, tests/specs/graph/jsr/FastCheckCache_Basic.txt, tests/specs/graph/jsr/FastCheckCache_DiagnosticThenNestedDep.txt, tests/specs/graph/jsr/FastCheck_AliasedNeverType.txt, tests/specs/graph/jsr/FastCheck_ClassGettersAndSetters.txt, tests/specs/graph/jsr/FastCheck_ClassProperties.txt, tests/specs/graph/jsr/FastCheck_ClassPropertiesLeavable.txt, tests/specs/graph/jsr/FastCheck_ClassSuper.txt, tests/specs/graph/jsr/FastCheck_Comments.txt, tests/specs/graph/jsr/FastCheck_DefaultExportExprVar.txt, tests/specs/graph/jsr/FastCheck_Enums.txt, tests/specs/graph/jsr/FastCheck_Functions.txt, tests/specs/graph/jsr/FastCheck_InferredUniqueSymbols.txt, tests/specs/graph/jsr/FastCheck_Issue22544.txt, tests/specs/graph/jsr/FastCheck_Methods.txt, tests/specs/graph/jsr/FastCheck_RefVarType.txt, tests/specs/graph/jsr/FastCheck_TypeAssertion.txt, tests/specs/graph/jsr/FastCheck_VarArrowLeavable.txt, tests/specs/graph/jsr/FastCheck_VarFunctionLeavable.txt, tests/specs/graph/jsr/FastCheck_Vars.txt
This works in more scenarios.
```ts
export type NeverType = never;
/**
* This should have `return {} as never` instead of `as any`, which would error when type checking.
*/
export function myFunction(): NeverType {
return {} as never;
}
```
=> fix(fast_check): use `as never` instead of `as any`

src/fast_check/mod.rs, src/fast_check/range_finder.rs
They shouldn't be surfaced because with byonm, modules in the node_modules directory are external.
Part of https://github.com/jsr-io/jsr/issues/323
=> fix(fast_check): should not surface errors for external modules

src/graph.rs, tests/specs/graph/jsr/DynamicImportOfJsr.txt
This is a bug that's existed for a long time. Previously a JSR specifier would not be resolved in a dynamic import if it was the last thing being resolved.
=> fix: jsr specifiers sometimes not resolved in dynamic imports

src/graph.rs, src/lib.rs
Previously, when a slow type was added to a file, the fast check was skipped, and all specifiers were checked. This new option, if toggled, allows you to check all specifiers anyway.
We should add a test, but I'm not sure how to.
Towards fixing https://github.com/denoland/deno/issues/23023
=> feat: `follow_fast_check_modules` option for conditional walking of fast check modules

src/fast_check/transform.rs, tests/specs/graph/jsr/FastCheck_Overloads.txt
Fixes https://github.com/jsr-io/jsr/issues/376
=> fix(fast_check): properly handle rest parameters in overloads

Cargo.lock, Cargo.toml, src/fast_check/transform.rs, src/graph.rs, tests/integration_test.rs
Makes the graph `Send` again.
Will test this out in the CLI before merging.
=> fix: store multi-threaded comments in the dts fast check module

src/graph.rs, src/lib.rs
Will do a patch release for this one. It's compiling in the CLI.
=> fix: make fast check `WalkOption` name more clear

src/fast_check/transform.rs, tests/specs/graph/jsr/FastCheck_Overloads.txt
Previously rest parameters had an optional type annotation added to them when generated for overload positions. This is wrong.
Additionally rest parameters in overloaded constructors were not handled correctly at all.
Fixes a bug introduced in #432
And properly fixes https://github.com/jsr-io/jsr/issues/376
I ran the output in the test case thru TSC, and it is happy with it now.
=> fix(fast_check): correctly handle rest parameters

src/graph.rs
This can be used in `Document::maybe_with_new_resolver()` to recompute resolutions without using `Document::maybe_parsed_source`.
We shouldn't be holding references to parsed/raw sources for non-open documents in memory. This would eliminate one usage.
=> feat: add Dependency::with_new_resolver()

Cargo.lock, Cargo.toml, README.md, js/loader.ts, js/mod.ts, js/test.ts, js/types.ts, lib/lib.rs, src/fast_check/transform_dts.rs, src/graph.rs, src/lib.rs, src/source/mod.rs, tests/helpers/mod.rs, tests/integration_test.rs, tests/specs/graph/multiple_redirects.txt, tests/specs_test.rs
Part of https://github.com/jsr-io/jsr/issues/322
This is necessary because someone may have a server that does a redirect to a JSR HTTPS URL and we'll need to detect that then use the manifest information to get the url's checksum.
The security issue this prevents against is:
1. The user has `"vendor": true`
2. deno_graph requests to load `https://example.com/mod.ts` with no checksum because it's not a jsr package.
3. That does a redirect to `https://jsr.io/@scope/pkg/0.1.0/mod.ts`, the CLI loads that url and stores it in the vendor folder without checking any checksum
4. The loader returns back `https://jsr.io/@scope/pkg/0.1.0/mod.ts`, but it's too late because the source has been stored in the vendor folder without its checksum being checked (once a file from jsr is in the vendor …
=> refactor: move redirect handling into deno_graph

Cargo.lock, Cargo.toml, src/analyzer.rs, src/ast.rs, src/fast_check/range_finder.rs, src/graph.rs, src/lib.rs, tests/specs/graph/fast_check/dts.txt
This commit adds a `@ts-self-types="..."` pragma that
may be placed at the top of untyped code files,
such as JS and JSX files. The specifier in this
pragma will then be used as the types for this
file when it is imported into a different file.
This is effectively the same as the existing
`/// <reference types="..." />` support in untyped
files, but with the added benefit of not
overloading the TypeScript triple-slash directive
syntax, and working with block comments.
Closes #442
=> feat(unstable): add support for @ts-self-types pragma

src/fast_check/range_finder.rs, tests/specs/graph/fast_check/issue_23658_1.txt, tests/specs/graph/fast_check/issue_23658_2.txt
We were tracing into a class' static method in this scenario, but not tracing the parent class.
```
> ../deno/target/debug/deno publish --dry-run
Checking for slow types in the public API...
Check file:///V:/ts-rpc/client.ts
Check file:///V:/ts-rpc/adapters/oak.ts
Simulating publish of @andykais/ts-rpc@0.1.0 with files:
file:///V:/ts-rpc/.github/workflows/deno.yml (1.01KB)
file:///V:/ts-rpc/README.md (2.6KB)
file:///V:/ts-rpc/adapters/mod.ts (2.91KB)
file:///V:/ts-rpc/adapters/oak.ts (2.32KB)
file:///V:/ts-rpc/client.ts (7.36KB)
file:///V:/ts-rpc/deno.jsonc (380B)
file:///V:/ts-rpc/deno.lock (31.6KB)
file:///V:/ts-rpc/server.ts (1.89KB)
file:///V:/ts-rpc/src/contracts.ts (1.41KB)
file:///V:/ts-rpc/src/errors.ts (4.12KB)
file:///V:/ts-rpc/src/types.ts (2.17KB) …
```
=> fix: trace parent classes and interfaces of referenced qualified expressions

src/graph.rs, tests/specs/graph/jsr/import_via_https_valid_checksum.txt, tests/specs/graph/jsr/import_via_https_with_deps.txt
Currently just have the failing tests here.
For https://github.com/denoland/deno/issues/23644
=> fix(jsr): https import of jsr dep that has a dependency

src/symbols/analyzer.rs
Need this for getting jsdocs in deno_doc.
=> fix: `ExpandoPropertyRef` - expose inner assignment expr

src/rt.rs
It was downloading jsr metadata files sequentially.
=> perf: call spawn immediately in tokio executor

lib/lib.rs, src/graph.rs, src/lib.rs
The main point of this PR was the refactor for parse_module to take a struct instead of having so many arguments. Then I noticed the specifier is always cloned so it can be taken as owned instead.
=> refactor(BREAKING): parse_module - take owned specifier

tests/specs/graph/fast_check/cache__diagnostic.txt, tests/specs/graph/fast_check/cache__diagnostic_deep.txt, tests/specs/graph/fast_check/cache__diagnostic_multiple_exports.txt, tests/specs/graph/fast_check/cache__diagnostic_then_nested_dep.txt, tests/specs/graph/fast_check/class_member_ref_additional_prop_on_member.txt, tests/specs/graph/fast_check/class_member_ref_not_found.txt, tests/specs/graph/fast_check/class_static_member_ref_not_found.txt, tests/specs/graph/fast_check/class_super_unsupported.txt, tests/specs/graph/fast_check/const_infer_function_missing_return.txt, tests/specs/graph/fast_check/cross_file_ref_module_not_found.txt, tests/specs/graph/fast_check/entrypoint_js.txt, tests/specs/graph/fast_check/expando_props/same_name_local_var_ref.txt, tests/specs/graph/fast_check/expando_props/same_name_namespace_export.txt, tests/specs/graph/fast_check/export_equals.txt, tests/specs/graph/fast_check/global_module.txt, tests/specs/graph/fast_check/inferred_unique_symbols__not_global.txt, tests/specs/graph/fast_check/missing_return_type.txt, tests/specs/graph/fast_check/missing_return_type_generator.txt, tests/specs/graph/fast_check/nested_java_script.txt, tests/specs/graph/fast_check/require.txt, tests/specs/graph/fast_check/return_inference/multiple_value_return_err.txt, tests/specs/graph/fast_check/return_inference/no_return_err.txt, tests/specs/graph/fast_check/return_inference/value_return_err.txt, tests/specs/graph/fast_check/ts_namespace_export.txt, tests/specs/graph/fast_check/unsupported_ambient_decl.txt, tests/specs/graph/fast_check/unsupported_default_export_expr.txt, tests/specs/graph/fast_check/unsupported_destructuring.txt, tests/specs/graph/fast_check/unsupported_private_member_ref.txt, tests/specs/graph/fast_check/unsupported_using_public_api.txt, tests/specs_test.rs
This allows us to ensure the accuracy of the printed diagnostics does not regress.
=> chore: use pretty diagnostics in spec tests

src/graph.rs, src/packages.rs, tests/specs/graph/jsr/https_redirect_to_jsr_invalid_checksum.txt, tests/specs/graph/jsr/https_redirect_to_jsr_valid_checksum.txt, tests/specs/graph/jsr/redirect_content.txt, tests/specs/graph/redirects_circular.txt, tests/specs/graph/redirects_max.txt
I needed to move redirect handling to a higher level as as part of some graph optimization work (for storing checksums in deno_graph) and it turned out this unlocked this scenario.
This allows an https specifier to redirect to a jsr https url.
=> feat: support redirecting to jsr https urls

src/graph.rs, src/jsr.rs, src/packages.rs, src/source/mod.rs, tests/helpers/mod.rs, tests/specs/graph/checksums/invalid.txt, tests/specs/graph/checksums/jsr_pkg_fills.txt, tests/specs/graph/checksums/jsr_pkg_invalid.txt, tests/specs/graph/checksums/jsr_pkg_valid.txt, tests/specs/graph/checksums/redirect_with_checksum.txt, tests/specs/graph/checksums/redirected_to_invalid.txt, tests/specs/graph/checksums/valid.txt, tests/specs_test.rs
Also it better organizes the code.
=> perf: move jsr manifest checksum to locker

src/fast_check/transform.rs, tests/specs/ecosystem/geacko/resp3_parser/1_1_1.test, tests/specs/ecosystem/geacko/resp3_parser/1_1_2.test, tests/specs/ecosystem/geacko/resp3_parser/1_1_3.test, tests/specs/ecosystem/geacko/resp3_parser/1_1_4.test, tests/specs/ecosystem/geacko/resp3_parser/1_1_6.test, tests/specs/ecosystem/geacko/resp3_parser/1_1_7.test, tests/specs/graph/fast_check/class_super.txt
For https://github.com/denoland/deno/issues/24051
=> fix(fast_check): super expr with spread

src/graph.rs, src/lib.rs
Mainly 1, but rarely 2:
1. This better represents the data because there can't be duplicates.
2. It will make us more performant if someone has hundreds of thousands of dynamic imports (which is a secenario I never benchmarked tbh).
Used an `IndexSet` instead of `BTreeSet` because knowing the first specifier is sometimes useful.
=> refactor: use an `IndexSet` for the graph roots

src/graph.rs, src/lib.rs, src/source/mod.rs, tests/helpers/mod.rs, tests/integration_test.rs
Most of the tests for this are in the CLI. This simplifies some stuff in deno_graph and makes it possible for a single dynamic npm import to fail resolution.
=> fix: resolve dynamic npm specifiers one at a time

Cargo.lock, Cargo.toml, tests/specs/ecosystem/codehz/mutable_element/0_2_0.test, tests/specs/ecosystem/codehz/mutable_element/0_2_1.test, tests/specs/ecosystem/codehz/mutable_element/0_2_2.test, tests/specs/ecosystem/happy_js/happy_opfs/1_0_0.test, tests/specs/ecosystem/stump/adapter_filesystem/0_0_1.test, tests/specs/ecosystem/ydcjeff/ruta/0_0_1.test, tests/specs/graph/fast_check/mapped_type.txt
=> fix(fast_check): emit named type in mapped types

src/graph.rs, tests/specs/graph/jsr/imported_multiple_packages.txt
For https://github.com/denoland/deno/issues/24536
=> fix: improve dependency tracking

src/graph.rs, src/jsr.rs, tests/integration_test.rs
For https://github.com/denoland/deno/issues/23965
=> fix: cache bust jsr meta file when version not found for dynamic branches

src/graph.rs
When there is a `jsxImportSource` and no `jsxImportSourceTypes`, we need to try and resolve the same specifier with `ResolutionMode::Types` to see if it resolves somewhere else, as we do with ES deps.
I hit this bug in the LSP specifically when using jsx import source `npm:preact` with byonm.
=> fix: resolve jsxImportSource with types mode in absence of jsxImportSourceTypes

src/fast_check/range_finder.rs, src/fast_check/transform.rs, src/graph.rs, src/lib.rs, src/symbols/cross_module.rs
1. Conditionally allocates the redirect HashSet.
2. Returns a reference from `graph.resolve` instead of cloning.
=> perf: avoid allocations in graph.resolve

src/fast_check/transform_dts.rs, tests/specs/graph/fast_check/class_properties_computed.txt
Closes https://github.com/denoland/deno_graph/issues/518
=> fix(fast_check/dts): better handling of computed properties

src/graph.rs, tests/ecosystem_test.rs, tests/specs/ecosystem/bureaudouble/bureau/0_0_98.test, tests/specs/graph/cjs_errors.txt, tests/specs_test.rs
This disallows cjs modules in deno_graph, but we'll support them in the CLI by changing the loader to mark them as external for file specifiers only.
=> fix: disallow cjs modules in deno_graph

js/types.ts, src/source/mod.rs
Part of https://github.com/denoland/deno/issues/17703
The `map` field has been empty for years now and we don't want the `emit` file to be exposed so it allows us to iterate on making the cache faster. Additionally, it's racy to rely on this information. Instead, people should emit the TS files themselves.
=> fix: CachedInfo - remove unused emit and map field

src/graph.rs, src/jsr.rs, src/source/mod.rs
This can be used to tell if a dynamic import was statically analyzable in the CLI.
=> feat: include if root was dynamic in load options

src/analyzer.rs, src/ast.rs, src/graph.rs, src/lib.rs, tests/specs/ecosystem/amit/neon_serverless_driver/0_0_3.test, tests/specs/ecosystem/kwhinnery/animals/0_0_14.test, tests/specs/ecosystem/kwhinnery/animals/0_0_15.test, tests/specs/ecosystem/kwhinnery/animals/0_0_16.test, tests/specs/ecosystem/kwhinnery/animals/0_0_17.test, tests/specs/ecosystem/neon/serverless/0_9_0.test, tests/specs/ecosystem/neon/serverless/0_9_2.test, tests/specs/graph/jsr/module_graph_info_1.txt, tests/specs/graph/jsr/module_graph_info_1_leading_comments.txt, tests/specs/graph/jsr/module_graph_info_2.txt, tests/specs/graph/jsr/module_graph_info_modified_cached_files.txt, tests/specs/graph/jsr/same_package_multiple_times.txt
Renames `Import::range` to `Import::specifier_range`, adds `Import::full_range`.
Towards https://github.com/denoland/deno/issues/18884.
=> feat: provide full import statement range

src/graph.rs, tests/integration_test.rs
Basically carry the "rootness" around until the specifier is fully resolved. Once it's resolved, store the resolved specifier in a separate set for later comparison.
This fixes an issue where we would error on `JSON` roots. Ref https://github.com/denoland/deno/issues/26509
=> fix: store resolved root specifiers

src/analyzer.rs, src/ast.rs, tests/specs/ecosystem/mrii/rocket_io/0_1_3.test
For https://github.com/denoland/deno/issues/25516
=> fix: analyze jsdoc import declarations

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, rust-toolchain.toml
Reverts denoland/deno_graph#546
This breaks the CLI due to the deno_ast upgrade and we've yet to land https://github.com/denoland/deno_graph/commit/0c979772b5789f095074f200eae127acdf7845ae (I need to release with https://github.com/denoland/deno_graph/commit/684eb1a570c0af5b9b15ff3bee7cceed9fc64368 and including this other PR adds too much of a change at once)
=> Revert "chore: upgrade deno_ast, deno_semver, thiserror"

Cargo.lock, Cargo.toml, src/source/wasm.rs
I updated the crate name to be more general and not apply to just strings.
=> chore: update string_capacity to capacity_builder

src/fast_check/transform.rs, tests/specs/graph/fast_check/issue_27575.txt
For https://github.com/denoland/deno/issues/27575
=> fix(fast_check): remove array elements in internal impl for spread exprs

src/graph.rs, src/lib.rs, tests/specs/ecosystem/mrii/rocket_io/0_1_3.test
Provides the ability to walk the graph resolving the check_js value based on the specifier.
This is required for having multiple tsconfig options in a workspace.
=> feat: custom check_js resolver when walking graph

src/graph.rs, tests/integration_test.rs, tests/specs/ecosystem/mrii/rocket_io/0_1_3.test
Wil fix https://github.com/denoland/vscode_deno/issues/1265#issuecomment-2691214305.
=> fix: respect lockfile when loading jsr specifiers

Cargo.lock, Cargo.toml, src/graph.rs, tests/specs/ecosystem/sxzz/ast_kit/0_12_0.test, tests/specs/ecosystem/sxzz/ast_kit/0_12_1.test
`deno_media_type` should have been released with a minor version because of the inbetween crate breakage.
=> fix: update deno_media_type to 0.2.8

src/graph.rs
For https://github.com/denoland/deno/pull/28578
=> fix: walk Wasm module resolution errors

lib/lib.rs, src/graph.rs, src/lib.rs, src/source/mod.rs, tests/ecosystem_test.rs, tests/helpers/mod.rs, tests/specs/ecosystem/mrii/rocket_io/0_1_3.test, tests/specs/graph/cjs/basic.txt
We should have this in deno_resolver instead.
CLI PR:
* https://github.com/denoland/deno/pull/29000
=> refactor: remove bare node builtin resolution from deno graph

src/fast_check/mod.rs, src/fast_check/range_finder.rs, src/graph.rs, src/lib.rs, src/symbols/analyzer.rs, tests/integration_test.rs, tests/specs_test.rs
This reverts commit 6429114237dd9c49d59bde7c6663a4b89444d954.
I think it's too complicated because we need to keep most of this around for doing stuff like getting the original source text when displaying errors: https://github.com/denoland/deno/blob/8687526f947fbaeafd3f0dd0652d30ab95585170/cli/module_loader.rs#L1197-L1201
Additionally, it brings some complications around how this would work once we have the ability to import bytes and text as we need the original bytes around. I think we should revist this in the future once we land `{ type: "bytes" }` and `"text"`.
=> Revert "feat: allow source of modules to be removed from the graph (#579)"

lib/lib.rs, src/fast_check/transform_dts.rs, src/graph.rs, src/jsr.rs, src/lib.rs, src/source/mod.rs, tests/ecosystem_test.rs, tests/helpers/mod.rs, tests/integration_test.rs
Somewhat of a naive remove and reload because it does not update the graph in anyway to remove dependencies of the reloaded specifiers.
=> feat: ability to reload certain specifiers and store mtime in graph

lib/lib.rs, src/graph.rs, src/source/mod.rs, tests/ecosystem_test.rs
Makes it easier for me to move out the loader trait completely from the CLI crate and this is more SRP anyway.
=> refactor: split off cache_module_info from the Loader trait

src/graph.rs, src/jsr.rs, src/packages.rs, tests/specs/graph/checksums/uses_lockfile_checksum.txt
Part of https://github.com/denoland/deno/issues/29432
Corresponding fix and more details in https://github.com/denoland/deno_cache_dir/pull/82
=> fix: use lockfileChecksum property for locker if set on jsr version metadata

src/analysis.rs, src/ast/dep.rs, src/ast/mod.rs, src/graph.rs, src/lib.rs, tests/specs/ecosystem/mrii/rocket_io/0_1_3.test
This is useful information to store. Currently not used.
=> feat: store if import is side effect import

src/graph.rs, tests/specs/graph/dts_files.txt, tests/specs/graph/fast_check/dts.txt
We were doing code resolution and types resolution for specifiers in dts files, which doesn't make sense.
=> fix: do not do execution resolution for declaration file dependencies
